### ISSUE TITLE
116 wrong rec length

### ISSUE THREAD

**Issue by hhyqq** [ZhenfaZheng/NAMDwithSOC#1]

**Comment by Ionizing** [comment]
Please upload the `inp` file and one of the `NormalCAR` so that we can inspect the issue.

**Comment by hhyqq** [comment]
[Uploading soc_issue.zip…]()

**Comment by hhyqq** [comment]
[soc_issue.zip](https://github.com/ZhenfaZheng/NAMDwithSOC/files/15463454/soc_issue.zip)

**Comment by Ionizing** [comment]
I tested the [soc.F90](https://github.com/ZhenfaZheng/NAMDwithSOC/blob/668fbb2d93b80c9d710c96a97fe979e5b5740264/src/soc.F90) with the following code but found nothing wrong. Maybe more information about your environment including OS version and compiler version is needed.

- `main.F90`
```Fortran
PROGRAM MAIN
    USE calcsoc, ONLY: calcHmm
    IMPLICIT NONE

    INTEGER :: nbands
    INTEGER :: nkpts
    INTEGER :: ikpt
    INTEGER :: nproj
    COMPLEX(8), ALLOCATABLE :: Hmm(:,:)

    ! logic begins
    nbands = 200
    nkpts  = 1
    ikpt   = 1

    ALLOCATE(Hmm(2*NBANDS,2*NBANDS))

    CALL calcHmm("../0001/", nbands, nkpts, ikpt, Hmm)
    PRINT *, MAXVAL(REAL(CONJG(Hmm) * Hmm))

    CALL calcHmm("../0002/", nbands, nkpts, ikpt, Hmm)
    PRINT *, MAXVAL(REAL(CONJG(Hmm) * Hmm))
END PROGRAM
```

- Makefile
```Makefile
FC = gfortran # ifort is also OK.
FFLAGS = -g -O2

main.x: main.o soc.o
    $(FC) -o $@ $^ $(FFLAGS)

main.o: soc.o

%.o: %.F90
    $(FC) -o $@ -c $< $(FFLAGS)

run: main.x
    ./$<

clean:
    rm -rf *.x *.o *.mod
```

Compiled with gfortran 8.5.0 on Rocky Linux 8.7

**Comment by hhyqq** [comment]
The OS: VERSION="8.6 (Green Obsidian)"

The compiler: gcc (GCC) 8.5.0

**Comment by Ionizing** [comment]
Looks nothing special, I still cannot find what's wrong.

**Comment by Ionizing** [comment]
Could you please paste the output of `make run` here by compiling the code in the following?

[0001.zip](https://github.com/ZhenfaZheng/NAMDwithSOC/files/15469477/0001.zip)

**Comment by Ionizing** [comment]
Finally find this issue related to the environment. Close now.
